version: "3.9"

networks:
  panel_net:
    external:
      name: shared_ext

services:
  panel:
    container_name: panel
    image: img/panel
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - panel_net
